// LibConnect Dummy Data
export const FACILITIES_LIST = [
  { id: 'ac', name: 'AC', icon: 'snowflake-o', lib: 'FontAwesome' },
  { id: 'wifi', name: 'WiFi', icon: 'wifi', lib: 'FontAwesome' },
  { id: 'cctv', name: 'CCTV', icon: 'videocam', lib: 'Ionicons' },
  { id: 'water', name: 'Drinking Water', icon: 'water', lib: 'Ionicons' },
  { id: 'washroom', name: 'Washroom', icon: 'wc', lib: 'MaterialIcons' },
  { id: 'locker', name: 'Locker', icon: 'lock-closed', lib: 'Ionicons' },
  { id: 'newspaper', name: 'Newspaper', icon: 'newspaper-o', lib: 'FontAwesome' },
  { id: 'cabin', name: 'Personal Cabin', icon: 'person', lib: 'Ionicons' },
  { id: 'silence', name: 'Silence Zone', icon: 'volume-mute', lib: 'Ionicons' },
  { id: 'printing', name: 'Printing', icon: 'print', lib: 'Ionicons' },
  { id: 'backup', name: 'Power Backup', icon: 'flash', lib: 'Ionicons' },
];

export const dummyLibraries = [
  {
    id: '1',
    name: 'The Study Point Library',
    address: 'Basement, C-33, Pankaj Singhvi Marg, Lalkothi, Jaipur 302015',
    area: 'Lalkothi, Jaipur',
    totalSeats: 80,
    vacantSeats: 15,
    bookedSeats: 65,
    halfTime: { from: '6:00 AM', to: '2:00 PM', fee: 400 },
    fullTime: { from: '6:00 AM', to: '10:00 PM', fee: 800 },
    openTime: '24 Hours',
    isOpen24hrs: true,
    facilities: ['ac', 'wifi', 'cctv', 'newspaper', 'silence'],
    whatsapp: '9988378077',
    coords: { lat: 26.9124, lng: 75.7873 },
    photos: ['https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600'],
    rating: 4.5,
    ownerName: 'Rajesh Kumar',
  },
  {
    id: '2',
    name: 'Vision Reading Zone',
    address: '70/38, Patel Marg, Sector 7, Mansarovar, Jaipur 302020',
    area: 'Mansarovar, Jaipur',
    totalSeats: 100,
    vacantSeats: 32,
    bookedSeats: 68,
    halfTime: { from: '6:00 AM', to: '2:00 PM', fee: 300 },
    fullTime: { from: '6:00 AM', to: '10:00 PM', fee: 500 },
    openTime: '24 Hours',
    isOpen24hrs: true,
    facilities: ['ac', 'wifi', 'locker', 'cabin'],
    whatsapp: '9970833596',
    coords: { lat: 26.8466, lng: 75.7516 },
    photos: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=600'],
    rating: 4.7,
    ownerName: 'Sunil Sharma',
  },
  {
    id: '3',
    name: 'Infinity Library',
    address: '81A, Ashok Vihar, Gopalpura Bypass Rd, Triveni Nagar, Jaipur 302015',
    area: 'Gopalpura, Jaipur',
    totalSeats: 60,
    vacantSeats: 0,
    bookedSeats: 60,
    halfTime: { from: '6:00 AM', to: '2:00 PM', fee: 350 },
    fullTime: { from: '6:00 AM', to: '10:00 PM', fee: 600 },
    openTime: '6:00 AM - 10:00 PM',
    isOpen24hrs: false,
    facilities: ['ac', 'wifi', 'water', 'washroom'],
    whatsapp: '9988648754',
    coords: { lat: 26.8738, lng: 75.7404 },
    photos: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600'],
    rating: 4.2,
    ownerName: 'Mohan Verma',
  },
  {
    id: '4',
    name: 'Success Library',
    address: 'B-148, Nandkishore Parikh Marg, Tonk Road, Bapu Nagar, Jaipur 302015',
    area: 'Tonk Road, Jaipur',
    totalSeats: 50,
    vacantSeats: 8,
    bookedSeats: 42,
    halfTime: { from: '6:00 AM', to: '2:00 PM', fee: 400 },
    fullTime: { from: '6:00 AM', to: '11:00 PM', fee: 700 },
    openTime: '6:00 AM - 11:00 PM',
    isOpen24hrs: false,
    facilities: ['ac', 'cctv', 'newspaper', 'backup'],
    whatsapp: '9985667787',
    coords: { lat: 26.8847, lng: 75.8069 },
    photos: ['https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600'],
    rating: 4.3,
    ownerName: 'Priya Gupta',
  },
  {
    id: '5',
    name: 'Bright Future Library',
    address: '20, Ashok Vihar, Gurjar Ki Thadi, Vaishali Nagar, Jaipur 302019',
    area: 'Vaishali Nagar, Jaipur',
    totalSeats: 75,
    vacantSeats: 25,
    bookedSeats: 50,
    halfTime: { from: '6:00 AM', to: '2:00 PM', fee: 300 },
    fullTime: { from: '6:00 AM', to: '10:00 PM', fee: 550 },
    openTime: '7:00 AM - 10:00 PM',
    isOpen24hrs: false,
    facilities: ['wifi', 'water', 'washroom', 'printing'],
    whatsapp: '9981070467',
    coords: { lat: 26.9121, lng: 75.7216 },
    photos: ['https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=600'],
    rating: 4.4,
    ownerName: 'Ankit Jain',
  },
];

// Dummy students currently in library
export const dummyStudents = [
  { id: 's1', name: 'Arjun Meena', goal: 'UPSC Preparation', seat: 12, since: '2 hrs ago' },
  { id: 's2', name: 'Priya Sharma', goal: 'NEET 2026', seat: 34, since: '4 hrs ago' },
  { id: 's3', name: 'Ravi Yadav', goal: 'CA Foundation', seat: 7, since: '1 hr ago' },
  { id: 's4', name: 'Sneha Gupta', goal: 'B.Tech Sem 5', seat: 56, since: '30 min ago' },
];

// Dummy weekly revenue data
export const weeklyRevenue = [
  { day: 'Mon', amount: 3200 },
  { day: 'Tue', amount: 4100 },
  { day: 'Wed', amount: 3800 },
  { day: 'Thu', amount: 4500 },
  { day: 'Fri', amount: 3600 },
  { day: 'Sat', amount: 2800 },
  { day: 'Sun', amount: 2000 },
];

export default { FACILITIES_LIST, dummyLibraries, dummyStudents, weeklyRevenue };
